### ISSUE TITLE
Table Tooltip alignment is not proper

### ISSUE THREAD

**Issue by aaratichavan** [carbon-design-system/carbon-components-angular#1806]
Used ibmEllipsisTooltip in ibm-table but when we hover on one record and do scroll-down scroll-up alignment is changing

code 
`<ng-template #tableCellTemplate let-data="data">
  <span
    class="ellipsis table-cell-content-trigger"
    trigger="hover"
    [placement]="'bottom'"
    ibmEllipsisTooltip>
    {{ data.content || '-' }}
  </span>
</ng-template>`

[

https://user-images.githubusercontent.com/69956330/117240809-4d738d80-ae4f-11eb-8c33-c50c60441a13.mov

]

**Comment by subson** [comment]
We are also running into similar issue any update on this one? For us, in a pop-up modal the tooltip position doesn't stay next to icon when the page is scrolled. We tried offset: {x:<val>, y:<val>} but it still shows tooltip in different places for different screen sizes...

**Comment by Akshat55** [comment]
This issue is likely caused by setting `position` style property on parent element. Here is a code sandbox example of using tooltips in table cells:

https://codesandbox.io/s/carbon-components-angular-forked-82zpiw?file=/src/app/app.component.ts

![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/88c36b2f-f57e-459b-b8a5-6b15b22a8b4b)
