### ISSUE TITLE
Facing delay in opening modal from the table row data when there are significantly more rows or if the tables cells have custom templates.

### ISSUE THREAD

**Issue by dinpatna** [carbon-design-system/carbon-components-angular#2472]
## Detailed description

> Facing delay in opening modal from the table row data when there are significantly more rows or if the tables cells have custom templates.

> This is a bug.

> Issue is related to modals opening from table row data when there are 200 + rows with simple data or 20 + rows with custom templates in the cells.

> We expect the modal to open immediately instead of a delay.

> Firefox, Safari, Chrome.

> Carbon version is 13.1.1

> This issue is blocking our upcoming release.

## Steps to reproduce the issue

[Sandbox Url](https://codesandbox.io/s/carbon-components-angular-forked-gwqqwl?file=/src/app/sample/sample.component.scss)

1. load the page for the first time and then try opening the modal from overflow menu in the last column of the table.

## Additional information

* Issue with delay only happens for the first load. Subsequent loads are faster.
* There is no delay in showing the table UI but the delay is only for opening the modal/overflow menu from the table row.

**Comment by Akshat55** [comment]
So, this is a tricky one.

The delay for the modal scales with the number of rows, which is expected... More noticeable when we render rows in the thousands.

After looking at the code, there were a few things that can be improved in the **table component**, but they weren't the root cause. The two main issues I think are:

1. Number of rows
2. The overflow menu. (Main issue)

### Number of rows
When we render a lot of rows, the number of nodes painted onto the screen is a lot. To check the number of elements in your application, you can open the console & run: `ocument.getElementsByTagName("*").length`. When we have a lot of rows, we need to give the browser to render the elements & angular to assign the event listeners to the overflow menu components. To test this, open the code sandbox demo [in new window](https://gwqqwl.csb.app/). Wait 20 to 30 seconds, more if there are a lot of rows. After waiting, interact with the overflow menu. You will see that the modal opens instantly. 

### The overflow menu
So the main issue isn't the number of rows, most devices can handle rendering hundreds to thousands of rows with minimal lag. When playing around with [code sandbox](https://codesandbox.io/s/carbon-components-angular-forked-yikljj), I switched the overflow menu with a simple button. I noticed that on button click with hundreds of rows, the modal opens with a very little delay (approx. 2 to 3 seconds - not a lot since button isn't that complex compared to the overflow menu). So that tells me that there is a performance issue with the overflow menu. After taking a look at the code, I _**believe**_ the delay is caused by the directive registering the events to the host AND the as well as the the `DialogService` registering the dialog references.

So overall, not a good idea to add hundreds or thousands of table rows & there is an issue with overflow menu registering on page load.

Now, I'll try taking a look into this _when I get the chance_, but if the changes require a breaking change, I probably won't have a solution up immediately.
