### ISSUE TITLE
Expandable Tile: interactions with Expandable Tile children triggers tile's collapse

### ISSUE THREAD

**Issue by hubertmalkowski** [carbon-design-system/carbon-components-angular#2528]
## Detailed description

> Describe in detail the issue you're having.

Clicking children(eg button) inside Expandable Tile triggers its collapse 

> Is this issue related to a specific component?

Expandable tile

> What version of the Carbon Design System are you using?
    
"carbon-components-angular": "^4.72.1",

```html
<ibm-expandable-tile >
  <span class="bx--tile-content__above-the-fold tile-head" >
    Some Content
  </span>
  <div class="bx--tile-content__below-the-fold">
     <  !--  Button that closes a tile  -->
    <button ibmButton='secondary'>This button closes a tile</button>
  </div>
</ibm-expandable-tile>
```

**Comment by Akshat55** [comment]
This is the expected behavior in v10. In v11, there is a new variation for expandable tile, where you have to click the caret for it to expand.

Might not be the cleanest solution, but in v10 - I will add a onClick event which propagates the click event & you can preventDefault based on what was clicked? Ideally (at least in v10), we shouldn't have interactive components in the component.

**Comment by Akshat55** [comment]
Hi, after taking a look at the component template, it does NOT support adding a button (`ng-content` is wrapped inside a button). The reason for this is that you cannot have a button within a button. So from what I'm seeing, it is not supported in v10.

**Comment by hubertmalkowski** [comment]
Hi, thank you for your answer. Would migrating our project to v11 be worth now?

**Comment by Akshat55** [comment]
I would recommend waiting until end of Q2 (June 2023)! We will be making a stable release!
