### ISSUE TITLE
[Number input] When user enters comma (,) or period (.) in field, it gets emptied

### ISSUE THREAD

**Issue by camilasb** [carbon-design-system/carbon-components-angular#2597]
[Number input] When user enters comma (,) or period (.) in assigned value field, it gets emptied

## Detailed description

Component should not delete users input in field automatically.

## Steps to reproduce the issue

1. Open the link https://angular.carbondesignsystem.com/?path=/story/components-number--basic
2. Enter any number
3. Enter comma (,) or period (.)

https://github.com/carbon-design-system/carbon-components-angular/assets/20360162/9411da22-f35f-4389-81db-c0a3ffa7ca80

Actual Result: Field gets emptied
Expected Result: we should prevent users from entering comma (,) or period (.) chars instead if only integers are allowed

## Additional information

I've opened this bug for my developers and they mentioned it's Carbon's default behavior.
I could see it happen on Storybook above, but not sure if there should be a special implementation for that when field only allows integers.
Don't know either how to test with a different implementation where decimals only were allowed.

**Comment by Akshat55** [comment]
I believe this is a browser issue.

Played around with it & noticed it's working fine on Chrome but on Firefox the text is reset when entering a period. Another odd thing is that, when we enter a period first and enter the numbers, it works. 😅

We are listening for `input` events on the number input, on `inputChange`, the browser returns an empty string for `event.target.value`. Our logic is set so that when it is an empty string, we make the assumption that the user has cleared the text 🤔.

I'm assuming you started seeing this issue recently? Could be caused by a Firefox update -Perhaps we may have to report this issue to Firefox.

**Comment by camilasb** [comment]
I don't use Firefox actually, I'm in Chrome all the time 😅 (you can see it in the recording)
It's the first time we use this component in our apps, so must confess I don't how recent this behavior is.
At least is not related to cache, cause the tests I did were in anonymous mode.

**Comment by Akshat55** [comment]
Hi @camilasb, this should be resolved now - it will not clear the number input on decimal or comma enter.
