### ISSUE TITLE
[ibmTooltip]: ibmTooltip is not available as a directive anymore. 

### ISSUE THREAD

**Issue by AmirHussain93** [carbon-design-system/carbon-components-angular#2737]
## Detailed description
We were using this ibm-tooltip as a directive in angular 9 version. We recently moved to angular 16 and now with  new version of carbon components ibm tool tip is no longer available as a directive

> Describe in detail the issue you're having.
   Can you make this directive available?

> Is this a feature request (new component, new icon), a bug, or a general issue?
   Yes 

> Is this issue related to a specific component?
   cdsTooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
   we would like to have [cdsTooltip] like we used to have [ibmTooltip] in older version

> What browser are you working in?
    chrome

> What version of the Carbon Design System are you using?
 "carbon-components-angular": "^5.14.1",

## Additional information

https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/toggletip/toggletip.component.ts

**Comment by Akshat55** [comment]
Unfortunately, this is because the **_styling_** has changed in Carbon 11 resulting in tooltips now being inline. This had to be done to resolve accessibility issues related to tooltip in Carbon 10. You can see that when you inspect the element and open it, the content gets rendered within the tooltip component.

Currently, there is work being done to have the popover components positioned relative to an element using `floating-ui`. I don't see the `ibmTooltip` directive returning unfortunatley.

**Comment by AmirHussain93** [comment]
@Akshat55 thanks for the information. Is there any tentative date to have the popover components positioned relative to an element using floating-ui ?

**Comment by Akshat55** [comment]
Support for floating-ui (autoAlign) has been released under experimental.
