### ISSUE TITLE
[Accessibility]: It is not possible to navigate and click Data Table row using keyboard only.

### ISSUE THREAD

**Issue by Sayan-Kyn-Personal** [carbon-design-system/carbon-components-angular#2815]
[Accessibility]: It is not possible to navigate and click Data Table row using keyboard only.

> Describe in detail the issue you're having.
It is not possible to navigate and click Data Table row using keyboard only.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
<cds-table>

> What did you expect to happen? What happened instead? What would you like to see changed?
The row onClick function should get executed when Enter key is pressed

> What browser are you working in?
Chrome Version 122.0.6261.128

> What version of the Carbon Design System are you using?
carbon-components-angular@5.16.3
carbon-components@11.48.1

## Steps to reproduce the issue
1. Open data table component which has clickable row
2. Using the tab key navigate to any of the row
3. Hit Enter to execute the 'selectRow' function

Output: Function is not executed. Users need to click on the row using mouse to make it work

**Comment by Akshat55** [comment]
When you say select a row, are you referring to selecting a checkbox? If yes, the key used for interacting with the checkbox is `space`.

**Comment by Sayan-Kyn-Personal** [comment]
I am not referring to the checkbox but instead to the rowClick event as shown here 'https://github.com/carbon-design-system/carbon-components-angular/blob/master/src/table/stories/app-table.component.ts'.

The table in our case does not have a selection column.

**Comment by tulasigudibanda** [comment]
This issue seems to be occurring in the latest version of Chrome, whereas it functions as expected in older versions. 
It is observed when pressing the 'Enter' key during a keydown event on table rows.  
Old chrome version :  event.path exists
New chrome version : event.path does not exist

It could be related to https://chromestatus.com/feature/5726124632965120

<img width="702" alt="old-version-with-event path" src="https://github.com/carbon-design-system/carbon-components-angular/assets/47306803/f9218fee-fb8a-4739-9119-9abd8e4a555a">

<img width="639" alt="latest-chrome-deprecated-event path" src="https://github.com/carbon-design-system/carbon-components-angular/assets/47306803/fc3db6e4-d814-451a-b177-5625da7f4e6d">

**Comment by tulasigudibanda** [comment]
event.target.rowIndex can be used. 
@Sayan-Kyn-Personal , you may close this.
